#pragma once
// risk_types.hpp — Shared types for Layer 7 Risk Management
//
// Centralises enums and structs used across all risk modules:
//   1. RiskDecision    — three-state outcome of order evaluation
//   2. RiskEvalResult  — detailed evaluation result with reason
//   3. Position        — open position with PnL tracking
//   4. PortfolioSummary — aggregated snapshot of all open positions
//
// Thread safety:
//   - All structs are plain data; thread safety is enforced by the
//     containers that hold them (PositionManager, etc.)

#include "pulse/core/error.hpp"
#include "pulse/core/types.hpp"

#include <chrono>
#include <cstdint>
#include <string>

namespace pulse::risk
{

// ---------------------------------------------------------------------------
// RiskDecision — outcome of RiskManager::evaluate_order()
//
//   1. Approved  — order passes all checks, proceed as-is
//   2. Modified  — order is approved but with reduced quantity
//   3. Rejected  — order is blocked; reason_code explains why
// ---------------------------------------------------------------------------
enum class RiskDecision : std::uint8_t
{
    Approved, ///< Order passes all risk checks.
    Modified, ///< Order approved with reduced size.
    Rejected, ///< Order blocked by a risk rule.
};

// ---------------------------------------------------------------------------
// RiskEvalResult — detailed evaluation result
//
// Returned by RiskManager::evaluate_order() to communicate the outcome of
// all risk checks applied to a proposed order.
//
// Fields:
//   1. decision         — Approved, Modified, or Rejected
//   2. approved_qty     — Original or reduced quantity (0 if rejected)
//   3. reason_code      — ErrorCode::Ok if approved; specific code if rejected
//   4. reason_message   — Human-readable explanation for logging / debugging
// ---------------------------------------------------------------------------
struct RiskEvalResult
{
    RiskDecision decision;
    Quantity approved_qty;      ///< Original or reduced quantity.
    ErrorCode reason_code;      ///< ErrorCode::Ok if approved; specific code if rejected.
    std::string reason_message; ///< Human-readable explanation.

    RiskEvalResult()
        : decision{ RiskDecision::Approved }
        , approved_qty{ 0.0 }
        , reason_code{ ErrorCode::Ok }
        , reason_message{}
    {
    }
};

// ---------------------------------------------------------------------------
// Position — represents an open position in one symbol
//
// Tracks the full lifecycle of a position from entry to close:
//   1. position_id     — unique identifier generated by PositionManager
//   2. symbol / side   — trading pair and direction
//   3. quantity        — current open quantity (reduces on partial close)
//   4. entry_price     — volume-weighted average entry price
//   5. current_price   — latest mark price (updated from TickerCache)
//   6. unrealized_pnl  — mark-to-market PnL: (current - entry) * qty * direction
//   7. notional_value  — abs(quantity * current_price)
//   8. open_time       — when the position was opened
//   9. strategy_id     — owning strategy identifier for per-strategy queries
// ---------------------------------------------------------------------------
struct Position
{
    std::string position_id;  ///< Unique identifier (e.g. "BTC_USDT_Buy_1").
    Symbol symbol;            ///< Trading pair.
    Side side;                ///< Buy (long) or Sell (short).
    Quantity quantity;        ///< Current open quantity.
    Price entry_price;        ///< Volume-weighted average entry price.
    Price current_price;      ///< Latest mark price (from TickerCache).
    double unrealized_pnl;    ///< (current_price - entry_price) * qty * direction.
    double notional_value;    ///< abs(quantity * current_price).
    Timestamp open_time;      ///< When the position was opened.
    std::string strategy_id;  ///< Owning strategy identifier.

    Position()
        : position_id{}
        , symbol{}
        , side{ Side::Buy }
        , quantity{ 0.0 }
        , entry_price{ 0.0 }
        , current_price{ 0.0 }
        , unrealized_pnl{ 0.0 }
        , notional_value{ 0.0 }
        , open_time{}
        , strategy_id{}
    {
    }
};

// ---------------------------------------------------------------------------
// PortfolioSummary — aggregated snapshot of all open positions
//
// Computed on demand by PositionManager::portfolio_summary():
//   1. open_position_count  — total number of open positions
//   2. total_notional       — sum of notional values across all positions
//   3. total_unrealized_pnl — sum of unrealized PnL
//   4. net_exposure         — net directional exposure (long notional - short notional)
// ---------------------------------------------------------------------------
struct PortfolioSummary
{
    int open_position_count;      ///< Total number of open positions.
    double total_notional;        ///< Sum of notional values across all positions.
    double total_unrealized_pnl;  ///< Sum of unrealized PnL.
    double net_exposure;          ///< Net directional exposure (long - short notional).

    PortfolioSummary()
        : open_position_count{ 0 }
        , total_notional{ 0.0 }
        , total_unrealized_pnl{ 0.0 }
        , net_exposure{ 0.0 }
    {
    }
};

} // namespace pulse::risk
